### ISSUE TITLE
[Common][Feature]: Collections and FrozenCollections

### ISSUE THREAD

**Issue by jakubtobiasz** [eduroo/framework#3]
### Description

Relying on weakly typed arrays is not the way we'd like to go with. I believe creating a common set of `Collection` and `FrozenCollection` interfaces and abstract classes can improve Eduroo's codebase.

### Example
Currently:
```php
final class ParametersBag implements ParametersBagInterface
{
    /** @var array<ParameterDefinitionInterface> */
    private array $parameters = [];
}
```

After:
```php
final class ParametersBag implements ParametersBagInterface
{
    private FrozenParameterDefinitionsCollectioon $parameters = [];
}
```

Benefits:
- Type-guards on the lower level
- Less magic to meet the strictest levels of Psalm/PHPStan

### Tasks

- [ ] Add the possibility to create strong-typed collections
- [ ] Add the possibility to create read-only collections

### Target version

next major

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
